# Docs:
# - https://github.com/pi-hole/docker-pi-hole/
# - https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # Need Host for this in order to run Unbound
    network_mode: host
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${PASSWORD}
      FTLCONF_webserver_port: ${HOST_PORT}
      FTLCONF_dns_upstreams: ${DNS_UPSTREAMS}
      FTLCONF_dns_listeningMode: "LOCAL"
      # DHCP server settings
      FTLCONF_dhcp_active: ${DHCP_ACTIVE}
      FTLCONF_dhcp_start: ${DHCP_START}
      FTLCONF_dhcp_end: ${DHCP_END}
      FTLCONF_dhcp_router: ${DHCP_ROUTER}
      FTLCONF_dhcp_leaseTime: ${DHCP_LEASE}
      FTLCONF_dhcp_ipv6: "false"
      FTLCONF_misc_dnsmasq_lines: |-
        address=/.pi/${HOST_IP}
    volumes:
      - "./etc-pihole:/etc/pihole"
      - "./var-log-pihole:/var/log/pihole"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: unless-stopped

  unbound:
    container_name: unbound
    image: alpinelinux/unbound:latest
    network_mode: host
    volumes:
      - "./etc-unbound/unbound.conf:/etc/unbound/unbound.conf:ro"
    # Some Claude suggested settings, unsure of them.
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    restart: unless-stopped

  glances:
    image: nicolargo/glances:latest-full
    container_name: glances
    hostname: ${HOST_NAME}
    pid: host
    environment:
      GLANCES_OPT: "-w"
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
      - /:/rootfs:ro
    ports:
      - "61208:61208"
    restart: unless-stopped
